services:
  milvus-standalone:
    image: milvusdb/milvus:v2.6.0
    command: [ "milvus", "run", "standalone" ]
    environment:
      MINIO_REGION: us-east-1
      ETCD_ENDPOINTS: milvus-etcd:2379
      MINIO_ADDRESS: milvus-minio:9000
    ports:
      - 19530:19530
      - 9091:9091
    volumes:
      - milvus_data:/var/lib/milvus
    networks:
      - milvus_network
    depends_on:
      - milvus-etcd
      - milvus-minio
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/healthz" ]
      interval: 30s
      start_period: 90s
      timeout: 10s
      retries: 3
    security_opt:
      - seccomp:unconfined

  milvus-etcd:
    image: quay.io/coreos/etcd:v3.6.4
    command: etcd -advertise-client-urls=http://milvus-etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    networks:
      - milvus_network
    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  milvus-minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    command: minio server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - minio_data:/data
    networks:
      - milvus_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  etcd_data:
  minio_data:
  milvus_data:

networks:
  milvus_network:
