services:
  spark-iceberg:
    image: tabulario/spark-iceberg:3.5.5_1.8.1
    ports:
      - 8888:8888
      - 8080:8080
      - 4040-4056:4040-4056
      - 8081:8081
      - 18080:18080
      - 10000:10000
      - 10001:10001
    volumes:
      - ./config/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./code:/home/iceberg/code
      - warehouse_data:/home/iceberg/warehouse
      - notebooks_data:/home/iceberg/notebooks/notebooks
    networks:
      iceberg_network:
    depends_on:
      - hive

  hive:
    image: apache/hive:4.0.0
    environment:
      - SERVICE_NAME=metastore
    ports:
      - 9083:9083
    volumes:
      - warehouse_data:/home/iceberg/warehouse
    networks:
      iceberg_network:

networks:
  iceberg_network:

volumes:
  warehouse_data:
  notebooks_data:
