version: '3.5'

services:
  spark-iceberg:
    image: tabulario/spark-iceberg
    container_name: spark-iceberg
    build: spark/
    networks:
      iceberg_net:
    volumes:
      - warehouse_data:/home/iceberg/warehouse
      - notebooks_data:/home/iceberg/notebooks/notebooks
      - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./spark_iceberg.py:/home/iceberg/spark_iceberg.py
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    ports:
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 10001:10001

networks:
  iceberg_net:

volumes:
  warehouse_data: {}
  notebooks_data: {}
