services:
  spark-iceberg:
    image: tabulario/spark-iceberg:3.5.5_1.8.1
    ports:
      - 8888:8888             # Jupyter Notebook UI
      - 8080:8080             # Spark Master UI
      - 4040-4056:4040-4056   # Spark Driver UI
      - 8081:8081             # Spark Worker UI
      - 18080:18080           # Spark History Server UI
      - 10000:10000           # Spark JDBC Endpoint
      - 10001:10001           # Spark Rest Endpoint
    networks:
      iceberg_network:

networks:
  iceberg_network:

volumes:
  notebooks_data:
  warehouse_data:
