version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: hms-postgres
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hivepw
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d metastore"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks: [iceberg_network]

  # One-shot schema init (safe to re-run; it will no-op after first time)
  hive-metastore-init:
    image: apache/hive:4.0.0
    container_name: hive-metastore-init
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config/hive-site.xml:/opt/hive/conf/hive-site.xml:ro
      - ./drivers/postgresql-42.7.3.jar:/opt/hive/lib/postgresql.jar:ro
    entrypoint: ["/opt/hive/bin/schematool"]
    command: ["-initSchema", "-dbType", "postgres", "-verbose"]
    networks: [iceberg_network]

  hive-metastore:
    image: apache/hive:4.0.0
    container_name: hive-metastore
    depends_on:
      postgres:
        condition: service_healthy
      hive-metastore-init:
        condition: service_completed_successfully
    environment:
      SERVICE_NAME: metastore     # runs Thrift HMS on :9083
    ports:
      - 9083:9083
    volumes:
      - ./config/hive-site.xml:/opt/hive/conf/hive-site.xml:ro
      - ./drivers/postgresql-42.7.3.jar:/opt/hive/lib/postgresql.jar:ro
      - warehouse_data:/warehouse   # data/metadata files for Iceberg tables
    entrypoint: ["/bin/bash", "-c"]
    command: ["/opt/hive/bin/hive --service metastore"]
    networks: [iceberg_network]

  spark-iceberg:
    image: tabulario/spark-iceberg:3.5.5_1.8.1
    container_name: spark-iceberg
    depends_on:
      hive-metastore:
        condition: service_started
    ports:
      - 8888:8888
      - 8080:8080
      - 4040-4056:4040-4056
      - 18080:18080
      - 10000:10000
      - 10001:10001
    volumes:
      - ./config/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
      - ./code:/home/iceberg/code
      - warehouse_data:/warehouse
      - notebooks_data:/home/iceberg/notebooks/notebooks
    environment:
      SPARK_SQL_WAREHOUSE_DIR: /warehouse
    networks: [iceberg_network]

networks:
  iceberg_network:

volumes:
  pg_data:
  warehouse_data:
  notebooks_data:
