services:
  spark-iceberg:
    image: tabulario/spark-iceberg:3.5.5_1.8.1
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
    ports:
      - 8888:8888
      - 8080:8080
      - 4040-4056:4040-4056
      - 8081:8081
      - 18080:18080
      - 10000:10000
      - 10001:10001
    volumes:
      - ./config/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
      - ./code:/home/iceberg/code:ro
      - warehouse_data:/home/iceberg/warehouse
      - notebooks_data:/home/iceberg/notebooks/notebooks
    networks:
      iceberg_network:
    depends_on:
      - rest
      - minio

  rest:
    image: apache/iceberg-rest-fixture:1.10.0
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_S3_ENDPOINT=http://minio:9000
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_PATH__STYLE__ACCESS=true
    ports:
      - 8181:8181
    networks:
      iceberg_network:

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: [ "server", "/data", "--console-address", ":9001" ]
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - minio_data:/data
    networks:
      iceberg_network:

  mc:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    entrypoint: |
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
    networks:
      iceberg_network:
    depends_on:
      - minio

networks:
  iceberg_network:

volumes:
  warehouse_data:
  notebooks_data:
  minio_data:
